version: "3.3"

services:
  # ROS1 Base Image
  nvidia_ros1:
    build: 
      context: ./ros1_base
      dockerfile: Dockerfile
    image: nvidia_ros1:latest

  gazebo_sim:
    build:
      context: ./gazebo_sim
      dockerfile: Dockerfile
    image: tortoisebot-ros1-gazebo:latest
    hostname: tortoise-gazebo-sim
    # command: tail -f /dev/null
    command: bash -c "source /root/catkin_ws/devel/setup.bash && roslaunch tortoisebot_gazebo tortoisebot_playground.launch"
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://tortoise-gazebo-sim:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/simulation_ws/src/tortoisebot/:/root/catkin_ws/src/tortoisebot
    networks:
      - ros1_net

  slam:
    build:
      context: ./mapping
      dockerfile: Dockerfile
    image: tortoisebot-ros1-slam:latest
    hostname: tortoise-mapping
    restart: always
    depends_on:
      - gazebo_sim
    command: bash -c "source /root/catkin_ws/devel/setup.bash && roslaunch tortoisebot_slam mapping.launch"
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://tortoise-gazebo-sim:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/simulation_ws/src/tortoisebot/:/root/catkin_ws/src/tortoisebot
    networks:
      - ros1_net

  waypoint_action:
    build:
      context: ./waypoint_action
      dockerfile: Dockerfile
    image: tortoisebot-ros1-waypoints:latest
    hostname: tortoise-waypt
    restart: always
    depends_on:
      - gazebo_sim
    command: |
      bash -c "source /opt/ros/noetic/setup.bash &&
             catkin_make &&
             source /root/catkin_ws/devel/setup.bash &&
             rosrun course_web_dev_ros tortoisebot_action_server.py"
    environment:
      - ROS_MASTER_URI=http://tortoise-gazebo-sim:11311
    volumes:
      - ~/simulation_ws/src/course_web_dev_ros/:/root/catkin_ws/src/course_web_dev_ros
    networks:
      - ros1_net

networks:
  ros1_net: