version: "3.3"

services:
  # ROS1 Base Image
  ros-master:
    image: ros:noetic-ros-core
    command: roscore
    network_mode: host
    restart: always
    ports:
      - "11311:11311"

  firmware: 
    build:
      context: ./firmware
      dockerfile: Dockerfile
    image: ros1_firmware:latest
    hostname: tortoisebot-ros1-firmware
    command: bash -c "roslaunch tortoisebot_firmware bringup.launch"
    restart: always
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://ros-master:11311
    volumes:
      - /home/tortoisebot/.Xauthority:/root/.Xauthority 
      - ~/ros1_ws/src/tortoisebot/:/root/catkin_ws/src/tortoisebot
    network_mode: host
  
  slam: 
    build:
      context: ./mapping
      dockerfile: Dockerfile
    image: ros1_slam:latest
    hostname: tortoisebot-ros1-firmware
    command: bash -c "roslaunch tortoisebot_slam tortoisebot_slam.launch"
    restart: always
    environment:
      - DISPLAY
      - ROS_MASTER_URI=http://ros-master:11311
    volumes:
      - /home/tortoisebot/.Xauthority:/root/.Xauthority 
      - ~/ros1_ws/src/tortoisebot/:/root/catkin_ws/src/tortoisebot
    network_mode: host